micronaut:
  application:
    name: jgdledge-coroutines-vs-reactive

  caches:
    discovery-client:
      enabled: false

  server:
    port: 8080

  executors:
    io:
      type: fixed
      nThreads: 10
    event-processing-executor:
      type: scheduled
      core-pool-size: 10

  metrics:
    enabled: true
    binders:
      jvm:
        enabled: true
      uptime:
        enabled: true
      processor:
        enabled: true
      files:
        enabled: true
      logback:
        enabled: true
      netty:
        enabled: true
    export:
      prometheus:
        # Whether to enable the reporter. Could disable to local dev for example.
        enabled: true
        # How frequently to report metrics. Default: PT1M (1 min).
        step: PT1M
        # Boolean if meter descriptions should be sent to Prometheus.
        # Turn this off to minimize the amount of data sent on each scrape. Default: true
        descriptions: true

grpc:
  server:
    port: 50051
    keep-alive-time: 3h
    max-inbound-message-size: 5120
    health:
      enabled: true

  # Default client config.  Specific channels can override with grpc.channels.<name>
  client:
    # Note: grpc.client.discovery.enabled is used by GrpcNameResolverProvider
    discovery:
      enabled: false
    plaintext: true
    max-retry-attempts: 5

endpoints:
  metrics:
    enabled: true
    sensitive: false
  prometheus:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
    # "anonymous" allows anyone to see details.  Change to "never" to disable.
    details-visible: anonymous
